version: '3.9'

services:
  frontend:
    build:
      context: ./brainly-fronted
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./brainly-fronted:/app
      - /app/node_modules
    command: npm run dev  # ensure Vite runs in dev mode

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://mongo:27017/mydb
    volumes:
      - ./backend:/app
      - /app/node_modules

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: